import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./App.css";
import StoreProvider from "@/redux/provider/StoreProvider";
import AuthChecking from "@/components/main/reuseable/AuthChecking/AuthChecking";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          {/* if we call AuthChecking here, then there will be problem for in seo i think.google/web crowler will find loader not the content */}
          {/* Next time try to sparate route into 2 categories - public and peivate route and group them differently and for private route,
          make a common layout where you called AuthChecking components and then it won't affect seo */}
          <AuthChecking>{children}</AuthChecking>
        </StoreProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
